import { Drink } from "./types";

export const drinks: Drink[] = [
  {
    id: "poke-bowl",
    name: "Poke Bowl",
    ingredients: ["Fresh ahi tuna", "Sushi rice", "Avocado", "Seaweed salad", "Sesame seeds", "Ponzu sauce"],
    hasNaOption: false,
    color: "from-rose-500 via-red-400 to-orange-400",
    image: "/drinks/poke.png",
    fontClass: "font-[family-name:var(--font-pacifico)]",
    glowColor: "shadow-rose-400",
    borderColor: "border-rose-300",
    emoji: "",
  },
  {
    id: "kalua-pork",
    name: "Kalua Pork",
    ingredients: ["Slow-roasted pork shoulder", "Hawaiian sea salt", "Banana leaves", "Steamed cabbage"],
    hasNaOption: false,
    color: "from-amber-700 via-amber-600 to-yellow-600",
    image: "/drinks/kalua.png",
    fontClass: "font-[family-name:var(--font-pacifico)]",
    glowColor: "shadow-amber-500",
    borderColor: "border-amber-400",
    emoji: "",
  },
  {
    id: "loco-moco",
    name: "Loco Moco",
    ingredients: ["Steamed rice", "Wagyu hamburger patty", "Farm-fresh fried egg", "Rich brown gravy"],
    hasNaOption: false,
    color: "from-yellow-600 via-amber-500 to-orange-500",
    image: "/drinks/loco.png",
    fontClass: "font-[family-name:var(--font-pacifico)]",
    glowColor: "shadow-yellow-400",
    borderColor: "border-yellow-300",
    emoji: "",
  },
  {
    id: "garlic-shrimp",
    name: "Garlic Shrimp",
    ingredients: ["Sauteed jumbo shrimp", "Roasted garlic butter", "White rice", "Fresh lemon"],
    hasNaOption: false,
    color: "from-orange-400 via-yellow-400 to-amber-300",
    image: "/drinks/shrimp.png",
    fontClass: "font-[family-name:var(--font-pacifico)]",
    glowColor: "shadow-orange-400",
    borderColor: "border-orange-300",
    emoji: "",
  },
  {
    id: "huli-huli-chicken",
    name: "Huli Huli Chicken",
    ingredients: ["Grilled free-range chicken", "Sweet soy glaze", "Grilled pineapple", "Macaroni salad"],
    hasNaOption: false,
    color: "from-yellow-500 via-orange-400 to-red-400",
    image: "/drinks/huli.png",
    fontClass: "font-[family-name:var(--font-pacifico)]",
    glowColor: "shadow-yellow-500",
    borderColor: "border-yellow-400",
    emoji: "",
  },
  {
    id: "spam-musubi",
    name: "Spam Musubi",
    ingredients: ["Grilled teriyaki spam", "Seasoned sushi rice", "Nori wrap", "Furikake"],
    hasNaOption: false,
    color: "from-emerald-600 via-green-500 to-teal-500",
    image: "/drinks/musubi.png",
    fontClass: "font-[family-name:var(--font-pacifico)]",
    glowColor: "shadow-emerald-400",
    borderColor: "border-emerald-300",
    emoji: "",
  },
  {
    id: "lau-lau",
    name: "Lau Lau",
    ingredients: ["Pork and butterfish", "Wrapped in taro leaves", "Steamed to perfection", "Sea salt finish"],
    hasNaOption: false,
    color: "from-green-700 via-emerald-600 to-lime-500",
    image: "/drinks/laulau.png",
    fontClass: "font-[family-name:var(--font-pacifico)]",
    glowColor: "shadow-green-400",
    borderColor: "border-green-300",
    emoji: "",
  },
  {
    id: "haupia",
    name: "Haupia",
    ingredients: ["Coconut milk pudding", "Tropical fruit medley", "Toasted coconut flakes", "Li hing mui dust"],
    hasNaOption: true,
    color: "from-amber-100 via-yellow-50 to-orange-100",
    image: "/drinks/haupia.png",
    fontClass: "font-[family-name:var(--font-pacifico)]",
    glowColor: "shadow-amber-200",
    borderColor: "border-amber-200",
    emoji: "",
  },
];

export function getDrinkById(id: string): Drink | undefined {
  return drinks.find((d) => d.id === id);
}
