import { Drink } from "./types";

export const drinks: Drink[] = [
  {
    id: "yoshis-egg",
    name: "Yoshi's Fertilized Egg",
    ingredients: ["Soju", "Sprite", "Melona"],
    hasNaOption: false,
    color: "from-green-400 via-lime-300 to-green-600",
    image: "/drinks/yoshi.png",
    fontClass: "font-[family-name:var(--font-pacifico)]",
    glowColor: "shadow-green-400",
    borderColor: "border-lime-300",
    emoji: "🥚",
  },
  {
    id: "waluigi-tales-flight",
    name: "Waluigi Tales Flight",
    ingredients: ["Gin", "Violette", "Maraschino", "Lemon"],
    hasNaOption: false,
    color: "from-purple-600 via-violet-500 to-indigo-700",
    image: "/drinks/waluigi.png",
    fontClass: "font-[family-name:var(--font-permanent-marker)]",
    glowColor: "shadow-purple-500",
    borderColor: "border-violet-400",
    emoji: "✈️",
  },
  {
    id: "brothers-highball",
    name: "Brothers Highball",
    ingredients: ["Gin", "Plum", "Shiso leaves"],
    hasNaOption: false,
    color: "from-red-500 via-green-500 to-red-600",
    image: "/drinks/brothers.png",
    fontClass: "font-[family-name:var(--font-bangers)]",
    glowColor: "shadow-red-400",
    borderColor: "border-green-400",
    emoji: "👨‍👨‍👦",
  },
  {
    id: "marios-bawlz",
    name: "Mario's Fire Baw3lz",
    ingredients: ["Vodka", "Sprite", "Grenadine"],
    hasNaOption: false,
    color: "from-red-600 via-red-500 to-yellow-500",
    image: "/drinks/mario.png",
    fontClass: "font-[family-name:var(--font-bangers)]",
    glowColor: "shadow-red-500",
    borderColor: "border-yellow-400",
    emoji: "🔥",
  },
  {
    id: "daisy",
    name: "Daisy",
    ingredients: ["Prosecco", "Mango puree", "Coconut cream", "Sago"],
    hasNaOption: true,
    color: "from-yellow-400 via-orange-400 to-amber-500",
    image: "/drinks/daisy.png",
    fontClass: "font-[family-name:var(--font-satisfy)]",
    glowColor: "shadow-yellow-400",
    borderColor: "border-orange-300",
    emoji: "🌼",
  },
  {
    id: "bowser-bomb",
    name: "Bowser Bomb",
    ingredients: ["Vodka", "Hot chocolate", "Oat milk", "Vanilla extract", "Cold foam", "Sprinkles"],
    hasNaOption: true,
    color: "from-orange-600 via-red-600 to-yellow-600",
    image: "/drinks/bowser.png",
    fontClass: "font-[family-name:var(--font-rubik-mono)]",
    glowColor: "shadow-orange-500",
    borderColor: "border-red-500",
    emoji: "💣",
  },
  {
    id: "donkey-kong",
    name: "Donkey Kong",
    ingredients: ["Bourbon", "Banana liqueur", "Kahlua", "Mozart", "Plaintain chip"],
    hasNaOption: false,
    color: "from-amber-700 via-yellow-600 to-amber-800",
    image: "/drinks/dk.png",
    fontClass: "font-[family-name:var(--font-special-elite)]",
    glowColor: "shadow-amber-500",
    borderColor: "border-yellow-500",
    emoji: "🍌",
  },
  {
    id: "bowser-space",
    name: "Bowser Space",
    ingredients: ["Surprise"],
    hasNaOption: true,
    color: "from-gray-800 via-purple-900 to-black",
    image: "/drinks/bowser-space.png",
    fontClass: "font-[family-name:var(--font-creepster)]",
    glowColor: "shadow-purple-600",
    borderColor: "border-purple-500",
    emoji: "❓",
  },
];

export function getDrinkById(id: string): Drink | undefined {
  return drinks.find((d) => d.id === id);
}
